### ISSUE TITLE
Screenshot font?

### ISSUE THREAD

**Issue by jdenen** [jamiecollinson/emacs-panda-theme#1]
What font are you using in your screenshot? It's beautiful.

**Comment by jdenen** [comment]
And I should say, I'm really enjoying the theme so far. Thanks for your work!

**Comment by jamiecollinson** [comment]
It's [Operator Mono](https://www.typography.com/blog/introducing-operator) which is expensive but nice. I'll add a link to the readme, and more screenshots is also on my todo list. 

I also think it looks good with [Triplicate](https://practicaltypography.com/triplicate.html):

![screen shot 2018-02-08 at 09 29 17](https://user-images.githubusercontent.com/3263722/35965371-96baa6aa-0cb2-11e8-9e38-0470d1a4fe16.png)

Thanks for the compliment and glad you're enjoying it! It's a bit of work in progress and also my first emacs theme, so I'm sure there's lots I've missed - any suggestions very welcome.

If you're a fan of this kind of theme you may also like https://draculatheme.com/emacs/ which I used for a long time.
